name: Build

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'lib/**'
      - 'python/**'
      - 'scripts/**'
      - 'launcher/drkcraft_launcher/**'
      - 'launcher/scripts/**'
      - 'CMakeLists.txt'
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Set up environment
        run: scripts\setup.bat --no-venv

      - name: Run Mypy
        run: scripts\mypy.bat

      - name: CMake build (Debug)
        run: python -m drkcraft build Debug --profile --dev

      - name: CMake build (Release)
        run: python -m drkcraft build Release

  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Set up environment
        run: |
          sudo apt-get install xorg-dev -y
          scripts/setup.sh --no-venv

      - name: Run Mypy
        run: scripts\mypy.sh

      - name: CMake build (Debug)
        run: python -m drkcraft build Debug --profile --dev

      - name: CMake build (Release)
        run: python -m drkcraft build Release
