name: CMake Build

on:
  push:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Set up environment
        run: scripts\setup.bat --no-venv

      - name: Run Mypy
        run: mypy --no-warn-no-return python\drkcraft # launcher\drkcraft_launcher

      - name: CMake build (Debug)
        run: python -m drkcraft build --debug --profile --dev

      - name: CMake build (Release)
        run: python -m drkcraft build --release

  Linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '>=3.10'

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Set up environment
        run: scripts/setup.sh --no-venv

      - name: Run Mypy
        run: mypy --no-warn-no-return python/drkcraft # launcher/drkcraft_launcher

      - name: CMake build (Debug)
        run: python -m drkcraft build --debug --profile --dev

      - name: CMake build (Release)
        run: python -m drkcraft build --release
