name: CMake Build

on:
  push:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Gen Glad
        run: scripts\gen_glad.bat

      - name: CMake build
        run: scripts\build.bat --debug
