name: CMake Build

on:
  push:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: CMake build (debug)
        run: scripts\build.bat --debug --profile --dev

      - name: CMake build (release)
        run: scripts\build.bat --release

      - name: CMake build (dist)
        run: scripts\build.bat --dist
  # Linux:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: CMake build
  #       run: scripts/build.sh --debug --profile --dev
