name: CMake Build

on:
  push:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: CMake build (Debug)
        run: scripts\win\build.bat --debug --profile --dev --trace

      - name: CMake build (Release)
        run: scripts\win\build.bat --release

  # Linux:
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2
  #       with:
  #         submodules: recursive

  #     - name: CMake build (Debug)
  #       run: scripts/lin/build.sh --debug --profile --dev --trace

  #     - name: CMake build (Release)
  #       run: scripts/lin/build.sh --release
